with open("C:/meteospot/lib/services/beach_service.dart", "r", encoding="utf-8") as f:
    lines = f.readlines()

dollar = chr(36)
new_func = []
new_func.append("  static Future<double?> _roadDistance(\n")
new_func.append("      double lat1, double lon1, double lat2, double lon2) async {\n")
new_func.append("    try {\n")
new_func.append(f"      final url = 'https://router.project-osrm.org/route/v1/driving/{dollar}{{lon1}},{dollar}{{lat1}};{dollar}{{lon2}},{dollar}{{lat2}}?overview=false';\n")
new_func.append("      final response = await http.get(Uri.parse(url)).timeout(const Duration(seconds: 5));\n")
new_func.append("      if (response.statusCode == 200) {\n")
new_func.append("        final data = jsonDecode(response.body);\n")
new_func.append("        final routes = data['routes'] as List?;\n")
new_func.append("        if (routes != null && routes.isNotEmpty) {\n")
new_func.append("          return (routes[0]['distance'] as num).toDouble() / 1000;\n")
new_func.append("        }\n")
new_func.append("      }\n")
new_func.append("    } catch (_) {}\n")
new_func.append("    return null;\n")
new_func.append("  }\n")
new_func.append("\n")
new_func.append("  static Future<List<Map<String, dynamic>>> findNearbyBeaches(\n")
new_func.append("      double lat, double lon, {int radiusKm = 50}) async {\n")
new_func.append("    final query = '[out:json][timeout:25];'\n")
new_func.append(f"        '(node[\"natural\"=\"beach\"](around:{dollar}{{radiusKm * 1000}},{dollar}lat,{dollar}lon);'\n")
new_func.append(f"        'way[\"natural\"=\"beach\"](around:{dollar}{{radiusKm * 1000}},{dollar}lat,{dollar}lon););'\n")
new_func.append("        'out center 15;';\n")
new_func.append("    final mirrors = [\n")
new_func.append("      'https://overpass-api.de/api/interpreter',\n")
new_func.append("      'https://overpass.kumi.systems/api/interpreter',\n")
new_func.append("      'https://overpass.openstreetmap.ru/api/interpreter',\n")
new_func.append("    ];\n")
new_func.append("    for (final mirror in mirrors) {\n")
new_func.append("      try {\n")
new_func.append("        final uri = Uri.parse(mirror).replace(queryParameters: {'data': query});\n")
new_func.append("        final response = await http.get(uri, headers: {\n")
new_func.append("          'User-Agent': 'MetAIoSpot/1.0 (gr.webdevelopment.metaiospot)'\n")
new_func.append("        }).timeout(const Duration(seconds: 15));\n")
new_func.append("        if (response.statusCode == 200) {\n")
new_func.append("          final data = jsonDecode(response.body);\n")
new_func.append("          final elements = data['elements'] as List? ?? [];\n")
new_func.append("          final beaches = <Map<String, dynamic>>[];\n")
new_func.append("          for (final e in elements) {\n")
new_func.append("            final tags = e['tags'] as Map? ?? {};\n")
new_func.append("            final name = tags['name'] ?? tags['name:el'] ?? 'Παραλία';\n")
new_func.append("            final eLat = (e['lat'] ?? e['center']?['lat']) as num?;\n")
new_func.append("            final eLon = (e['lon'] ?? e['center']?['lon']) as num?;\n")
new_func.append("            if (eLat != null && eLon != null) {\n")
new_func.append("              beaches.add({'name': name, 'lat': eLat.toDouble(), 'lon': eLon.toDouble(), 'distKm': 0.0});\n")
new_func.append("            }\n")
new_func.append("          }\n")
new_func.append("          if (beaches.isNotEmpty) return beaches;\n")
new_func.append("        }\n")
new_func.append("      } catch (_) { continue; }\n")
new_func.append("    }\n")
new_func.append("    // Fallback: use local list with OSRM road distance filter\n")
new_func.append("    final radiusDeg = radiusKm / 111.0;\n")
new_func.append("    final candidates = _greekBeachesFallback.where((b) {\n")
new_func.append("      final dlat = (b['lat'] as double) - lat;\n")
new_func.append("      final dlon = (b['lon'] as double) - lon;\n")
new_func.append("      return (dlat * dlat + dlon * dlon) <= radiusDeg * radiusDeg;\n")
new_func.append("    }).toList();\n")
new_func.append("    candidates.sort((a, b) {\n")
new_func.append("      final da = _distance(lat, lon, a['lat'] as double, a['lon'] as double);\n")
new_func.append("      final db = _distance(lat, lon, b['lat'] as double, b['lon'] as double);\n")
new_func.append("      return da.compareTo(db);\n")
new_func.append("    });\n")
new_func.append("    final results = <Map<String, dynamic>>[];\n")
new_func.append("    for (final b in candidates.take(20)) {\n")
new_func.append("      final roadDist = await _roadDistance(lat, lon, b['lat'] as double, b['lon'] as double);\n")
new_func.append(f"      if (roadDist != null && roadDist <= {dollar}{{radiusKm * 2}}) {{\n")
new_func.append("        results.add({'name': b['name'], 'lat': b['lat'], 'lon': b['lon'], 'distKm': double.parse(roadDist.toStringAsFixed(1))});\n")
new_func.append("        if (results.length >= 8) break;\n")
new_func.append("      }\n")
new_func.append("    }\n")
new_func.append("    if (results.isEmpty) return candidates.take(5).map((b) {\n")
new_func.append("      final dlat = (b['lat'] as double) - lat;\n")
new_func.append("      final dlon = (b['lon'] as double) - lon;\n")
new_func.append("      final distKm = (111.0 * (dlat * dlat + dlon * dlon).abs() * 0.5);\n")
new_func.append("      return {'name': b['name'], 'lat': b['lat'], 'lon': b['lon'], 'distKm': double.parse(distKm.toStringAsFixed(1))};\n")
new_func.append("    }).toList();\n")
new_func.append("    results.sort((a, b) => (a['distKm'] as double).compareTo(b['distKm'] as double));\n")
new_func.append("    return results;\n")
new_func.append("  }\n")
new_func.append("}\n")

new_lines = lines[:366] + new_func

with open("C:/meteospot/lib/services/beach_service.dart", "w", encoding="utf-8") as f:
    f.writelines(new_lines)

print("Done! Total lines:", len(new_lines))
